### ISSUE TITLE
Error Failed to parse string

### ISSUE THREAD

**Issue by Licen-it** [ryanluker/vscode-coverage-gutters#150]
I'm always getting this error when i try to use the extension. I tried adding the watch on `lcov.info` and `cobertura-coverage.xml`, but the error is the same and nothing get displayed on the source code.

Here is the screenshot of the extension output:
![image](https://user-images.githubusercontent.com/35496522/43193643-71ba00e8-8ff8-11e8-8dbb-79be669228e9.png)

**Comment by ryanluker** [comment]
@Licen-it thanks for submitting an issue! this is related to the score logic that was added recently and should be fixed in the next version of the extension I am working on (2.1.0). In the meantime you could try just loading lcov.info to see if that will help you til next release.

**Comment by ryanluker** [comment]
@Licen-it hmm the only other thing i would try before 2.1.0 would be to open the example workspace project here in this repo and see if the coverage shows up for you or not.

**Comment by ryanluker** [comment]
@Licen-it 2.1.0 is being released this afternoon (pst) to the marketplace. let me know if this release doesn't fix your issue and we can reopen the ticket and do some more investigating.

**Comment by ryanluker** [comment]
@Licen-it ahh yes the plugin does not look outside the project / workspace folder when it does the collection phase https://github.com/ryanluker/vscode-coverage-gutters/blob/master/src/filesloader.ts#L86 this is mainly to prevent looking everywhere in your computer for coverage files but I could imagine a feature where you say where your coverage folder is located and it wouldnt use the glob find in that case. Let me think about this for the 2.1.1 release but in the meantime can you not include your coverage inside your project folder?

**Comment by Licen-it** [comment]
@ryanluker ok...but i was wondering why aren't you using the paths in the coverage files (i can see `lcov.info` for each file provides the full path while `cobertura-coverage.xml` provides the top level folder path and then relative paths to each file)

**Comment by Licen-it** [comment]
Anyway i just checked putting the coverage file on top level folder and still not working...i'm still getting  the `Failed to parse string` error

**Comment by ryanluker** [comment]
@Licen-it the reasoning for not using the full paths in the cobertura one is that it has an `absPath` value that you send in to allow the parse to attach the absolute path when it returns you the coverage objects (https://github.com/ryanluker/vscode-coverage-gutters/commit/deee3d123769ea16c267d10e13290107dd8cbcfa#diff-3661d843d67f46cb9cfd476ad7e1920cR37). when you moved the coverage file (`cobertura-coverage.xml`  to inside the workspace folder did you also set the `xmlname` setting and restart your IDE? 
![temp2](https://user-images.githubusercontent.com/1335972/43587089-3c1fd77e-961e-11e8-82d8-1ee155e711d1.PNG)

**Comment by Licen-it** [comment]
@ryanluker nope. I moved the `lcov.info` top level...but maybe it's because i have multiple projects in my workspace and each of them have an `lcov.info`

**Comment by ryanluker** [comment]
@Licen-it thanks for getting back so quickly. hmm well I will take a look at this with the `2.1.1` bug fix release, the only over thing you could do is make an example repo with the reproducible bug to assist me in figuring out the issue or you could also run the extension in development mode locally and debug your project to see where that failed to parse string is coming from 😄 https://code.visualstudio.com/docs/extensions/developing-extensions#_running-and-debugging-your-extension

**Comment by Licen-it** [comment]
@ryanluker so workspace is structured as follows:

```
workspace
|___project1
|     |___coverage
|     |     |___lcov-report (dir with html report)
|     |     |___cobertura-coverage.xml
|     |     |___coverage-final.json
|     |     |___lcov.info
|     |___src (dir with all the code)
|     |___tests (dir with all tests)
|___project2
|     |___coverage
|     |     |___lcov-report (dir with html report)
|     |     |___cobertura-coverage.xml
|     |     |___coverage-final.json
|     |     |___lcov.info
|     |___src (dir with all the code)
|     |___tests (dir with all tests)
|___project3
|     |___coverage
|     |     |___lcov-report (dir with html report)
|     |     |___cobertura-coverage.xml
|     |     |___coverage-final.json
|     |     |___lcov.info
|     |___src (dir with all the code)
|     |___tests (dir with all tests)
```

**Comment by ryanluker** [comment]
@Licen-it I have done some rework on the coverage parsing and this maybe fixed in the next release (2.2.0) once it is out let me know if this is still an issue!

**Comment by Licen-it** [comment]
@ryanluker sorry for the long wait, i was able to check this just now, and i can still reproduce the issue

**Comment by ryanluker** [comment]
@Licen-it with the latest release (2.2.2) can you try to run the watch command on your project workspace again and paste the output from the gutters console tab like you did in the original ticket?

**Comment by Licen-it** [comment]
@ryanluker here you are...i noticed it's taking longer before falling into the error

![image](https://user-images.githubusercontent.com/35496522/48481369-349d3a80-e805-11e8-9424-f1a2813141f6.png)

**Comment by ryanluker** [comment]
@Licen-it thanks for the further info, we are getting closer. Can you install the (in development) 2.3.0 version of the extension below and paste the results from that?
[vscode-coverage-gutters-2.3.0.zip](https://github.com/ryanluker/vscode-coverage-gutters/files/2593166/vscode-coverage-gutters-2.3.0.zip)

**Comment by Licen-it** [comment]
@ryanluker same output:
![image](https://user-images.githubusercontent.com/35496522/48699524-8ff27280-ebe1-11e8-92a1-3e5356028bb7.png)

**Comment by ryanluker** [comment]
@Licen-it thanks for the continual assistance on this one, looks like @DW8Reaper has a new fix that may also help with your issues. I will message again once I have a new 2.3.0 pre-release for you to try.

**Comment by ryanluker** [comment]
@Licen-it the fix mentioned above has been added to the 2.3.0 release, I have include a pre-release version of that below for you to try when you have some free time. The fix will only work for lcov files currently but I plan to use the same fix @DW8Reaper applied but for the other coverage types as well.

[vscode-coverage-gutters-2.3.0.zip](https://github.com/ryanluker/vscode-coverage-gutters/files/2614097/vscode-coverage-gutters-2.3.0.zip)

**Comment by Licen-it** [comment]
@ryanluker with this version there is no error like the one in the console, the log stops at `Loaded 30 data file(s)` but no coverage appears in the files and removing the watch i'm getting this error message but still nothing in the output:
![image](https://user-images.githubusercontent.com/35496522/49021013-a3757e80-f189-11e8-8ceb-000b725e39f4.png)

**Comment by DW8Reaper** [comment]
@Licen-it check if any of your coverage filenames in vscode settings are empty. I had an issue where I cleared the xml config path which ended up trying to read every file in my repo as a coverage file. I actually got an error message though so might not be the same issue (https://github.com/ryanluker/vscode-coverage-gutters/pull/192)

**Comment by orsaz** [comment]
![image](https://user-images.githubusercontent.com/13506783/49093306-79e15380-f26c-11e8-850b-9e0ac5bef0e9.png)
I still get this error. 
Does lcov.info and cov.xml files have to be empty or i need to write something there?

**Comment by DW8Reaper** [comment]
Look better now the ```Loading 2 file(s)``` vs ```Loading 30 file(s)``` you had before. Now the fix I put in was only for lcov files not xml but @ryanluker was going to add it to the other types as well. If you have an lcov you can use perhaps put an invalid filename in to the xml field that way the file won't be found and won't load. This again is just a work around to try till the issue is fixed.

**Comment by Licen-it** [comment]
@DW8Reaper no i don't have any empty coverage filename in the settings

**Comment by DW8Reaper** [comment]
Shucks, must be a different issue then was hoping it would be the same one I had.

**Comment by Licen-it** [comment]
@ryanluker i'm getting the same error i mentioned in my comment above and still no gutters showing the code coverage.

![image](https://user-images.githubusercontent.com/35496522/49512632-79594600-f886-11e8-8c66-40a20735232e.png)

**Comment by ryanluker** [comment]
@Licen-it sorry this must have slipped through the cracks... it is still an issue with the latest version of the extension? Also can you paste the output from the extension log as well?

**Comment by Licen-it** [comment]
@ryanluker same issues as before with version 2.3.0...the screenshots above are still valid (i'm getting the same errors/logs). So when i hit `Watch` having `lcov.info` selected it loads correctly as showed below, but no gutters showing the code coverage. When i hit `Remove Watch` the error message in the picture in my comment on Dec 5th appears.

![image](https://user-images.githubusercontent.com/35496522/52271416-77ba0600-293b-11e9-8d92-9552d07b5e2a.png)

**Comment by ryanluker** [comment]
@Licen-it still looking into this one but I cannot reproduce it myself locally still, sadly. I have added additional logging here 4298597cba57e73cd22d3bf6aaf5edf6cea54a00 and it will be in the `2.3.1` release coming shortly. Hopefully in that new version we will get more insight where your error message is coming from.

**Comment by Licen-it** [comment]
@ryanluker here is the exception log when i remove the watch:

```
[1551281968268][coverageservice]: INITIALIZING
[1551284657194][coverageservice]: LOADING
[1551284674657][coverageservice]: Loading 38 file(s)
[1551284674680][coverageservice]: Loaded 38 data file(s)
[1551284706323][removeWatch]: Cannot read property 'dispose' of undefined
[1551284706323][removeWatch]: TypeError: Cannot read property 'dispose' of undefined
    at CoverageService.dispose (/Users/licen/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/coverage-system/coverageservice.js:37:30)
    at Gutters.removeWatch (/Users/licen/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/extension/gutters.js:72:34)
    at vscode.commands.registerCommand (/Users/licen/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/extension.js:28:17)
    at e._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:485:959)
    at e.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:486:443)
    at t._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:644:118)
    at t._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:643:744)
    at t._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:642:322)
    at t._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:641:155)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:638:960
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:38:994
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:113)
    at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:170:213)
    at Socket.f._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:170:434)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
```

**Comment by ryanluker** [comment]
@Licen-it it is odd you see the loaded data files message but nothing related to caching :thinking: see my local example run below.
```
[1553982083011][coverageservice]: INITIALIZING
[1553982096718][coverageservice]: LOADING
[1553982096789][coverageservice]: Loading 4 file(s)
[1553982096790][coverageservice]: Loaded 4 data file(s)
[1553982096813][coverageservice]: Caching 11 coverage(s)
[1553982096813][printDataCoverage]: Coverage ->
[1553982096813][printDataCoverage]: {
    "lines": {
         <coverage omitted>
    }
```
This usually means that one of the parsers encountered an error or is very slow (can you try again but wait for a while to see if anything finishes?). Also I recently did some cleanup of the cobertura-parse (which you would use based on some of the previous pictures in this thread) so maybe try the build below and get back to me if anything changes!

[vscode-coverage-gutters-2.4.0.zip](https://github.com/ryanluker/vscode-coverage-gutters/files/3025983/vscode-coverage-gutters-2.4.0.zip)

**Comment by Licen-it** [comment]
@ryanluker after 2h still nothing after `Loaded 38 data file(s)`

**Comment by ermshiperete** [comment]
Same for me. Gutters not showing. In the developer tools console I see the following exception:

```
mainThreadExtensionService.ts:49 [[object Object]]Cannot create property 'message' on string 'Failed to parse string'
mainThreadExtensionService.ts:50 TypeError: Cannot create property 'message' on string 'Failed to parse string'
	at checkError (/home/user/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/files/coverageparser.js:134)
	at CoverageParser.<anonymous> (/home/user/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/files/coverageparser.js:141)
	at Generator.next (<anonymous>)
	at __awaiter (/home/user/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/files/coverageparser.js:7)
	at new Promise (<anonymous>)
	at __awaiter (/home/user/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/files/coverageparser.js:3)
	at lcovExtract.lcov_parse_1.source (/home/user/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/files/coverageparser.js:140)
	at Function.walkFile [as source] (/home/user/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/node_modules/lcov-parse/lib/index.js:108)
	at lcovExtract.Promise (/home/user/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/files/coverageparser.js:140)
	at new Promise (<anonymous>)
	at CoverageParser.lcovExtract (/home/user/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/files/coverageparser.js:131)
	at CoverageParser.<anonymous> (/home/user/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/files/coverageparser.js:48)
	at Generator.next (<anonymous>)
	at fulfilled (/home/user/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.3.1/out/src/files/coverageparser.js:4)
```

**Comment by ryanluker** [comment]
@Licen-it opps I should have given you a time range to wait for (2min was more my thinking, sorry!).
We might be getting closer with @ermshiperete comment (thanks for this!) showing the more extensive stack trace. I will continue looking into this over the weekend!

**Comment by ermshiperete** [comment]
The PR fixes things at least in my case.

**Comment by ryanluker** [comment]
@Licen-it can you try this new version below that includes @ermshiperete 's fix?
[vscode-coverage-gutters-2.4.0-apr4.zip](https://github.com/ryanluker/vscode-coverage-gutters/files/3046101/vscode-coverage-gutters-2.4.0-apr4.zip)

**Comment by Licen-it** [comment]
@ryanluker this is working now. I have my coverage appearing finally. Thanks @ermshiperete for your PR. The only thing different from the video shown is that the gutters are appearing only at left side of row numbers and not in the code itself.

**Comment by ryanluker** [comment]
@Licen-it sweet this one is finally fixed, thanks for running the (almost 8 month long) marathon with me :laughing: !
You can modify where the coverage is displayed by turning off and of some settings
```
        "coverage-gutters.showLineCoverage": {
          "type": "boolean",
          "default": false,
          "description": "show or hide the line coverage"
        },
        "coverage-gutters.showRulerCoverage": {
          "type": "boolean",
          "default": false,
          "description": "show or hide the ruler coverage"
        },
        "coverage-gutters.showGutterCoverage": {
          "type": "boolean",
          "default": true,
          "description": "show or hide the gutter coverage"
        },
```
